### PR TITLE
DOC: Add PyPI, License badges

### PR DESCRIPTION
**Pull request by thewtex**

### CODE REVIEW

**Review by jhlegarreta — APPROVED** [review]

**Comment by jhlegarreta** [comment]
@thewtex a comment related to the badges: the `Build, test, package` badges' links point to an SVG file across many (all?) remote modules (maybe also in the `ITKModuleTemplate`). I'd dare to say that this is not really helpful: IMHO they should point to each repository's `master` branch in the `Action` tab e.g.:
https://github.com/InsightSoftwareConsortium/ITKIOFDF/actions/workflows/build-test-package.yml?query=branch%3Amaster

**Review by dzenanz — APPROVED** [review]

**Comment by dzenanz** [comment]
Jon, is your remark related to this PR? If so, I didn't quite understand what is wrong.

**Comment by jhlegarreta** [comment]
> Jon, is your remark related to this PR? If so, I didn't quite understand what is wrong.

Sorry, you're right. It is related to the CI badges, and thus not strictly related to the changes in this PR. Maybe the `ITKModuleTemplate` is the place to open an issue.

**Comment by thewtex** [comment]
@jhlegarreta good point -- tracked in https://github.com/InsightSoftwareConsortium/ITKModuleTemplate/issues/108

**Pull request merged**
